use crate::types::{Dependency, Severity};
use petgraph::graph::{DiGraph, NodeIndex};
use std::collections::HashMap;

pub struct DepGraph {
    pub graph: DiGraph<NodeData, EdgeData>,
    pub node_index: HashMap<String, NodeIndex>,
}

#[derive(Debug, Clone)]
pub struct NodeData {
    pub coord: String,
    pub version: String,
    pub is_direct: bool,
    pub risk: Option<Severity>,
}

#[derive(Debug, Clone)]
pub struct EdgeData {
    pub scope: Option<String>,
}

impl DepGraph {
    pub fn new() -> Self {
        Self {
            graph: DiGraph::new(),
            node_index: HashMap::new(),
        }
    }

    pub fn add_dependency(&mut self, dep: &Dependency, risk: Option<Severity>) -> NodeIndex {
        let coord = dep.coord();
        if let Some(&idx) = self.node_index.get(&coord) {
            return idx;
        }
        let idx = self.graph.add_node(NodeData {
            coord: coord.clone(),
            version: dep.version.clone(),
            is_direct: !dep.is_transitive,
            risk,
        });
        self.node_index.insert(coord, idx);
        idx
    }

    pub fn add_edge(&mut self, from: NodeIndex, to: NodeIndex, scope: Option<String>) {
        // Avoid duplicate edges
        if !self.graph.contains_edge(from, to) {
            self.graph.add_edge(from, to, EdgeData { scope });
        }
    }

    /// Build a synthetic parent→child structure (direct deps are roots)
    pub fn build_from_deps(
        direct: &[Dependency],
        transitive: &[Dependency],
        risk_map: &HashMap<String, Severity>,
    ) -> Self {
        let mut g = Self::new();

        // Add all direct deps
        for dep in direct {
            let risk = risk_map.get(&dep.coord()).cloned();
            g.add_dependency(dep, risk);
        }

        // Add transitive deps
        for dep in transitive {
            let risk = risk_map.get(&dep.coord()).cloned();
            g.add_dependency(dep, risk);
        }

        // For now, link transitive deps to a virtual root
        // In a full implementation, you'd parse dependency resolution output
        let root_coord = "__ROOT__".to_string();
        let root_idx = g.graph.add_node(NodeData {
            coord: root_coord.clone(),
            version: String::new(),
            is_direct: false,
            risk: None,
        });
        g.node_index.insert(root_coord, root_idx);

        for dep in direct {
            if let Some(&dep_idx) = g.node_index.get(&dep.coord()) {
                g.add_edge(root_idx, dep_idx, dep.scope.clone());
            }
        }

        g
    }

    /// Render as Graphviz DOT format with color-coded risk nodes
    pub fn to_dot(&self) -> String {
        use std::fmt::Write;
        let mut out = String::new();
        writeln!(out, "// Generated by scala-dep-scan").unwrap();
        writeln!(
            out,
            "// Risk: RED=Critical, ORANGE=High, YELLOW=Medium, GREEN=Low, BLUE=Direct"
        )
        .unwrap();
        writeln!(out, "digraph deps {{").unwrap();
        writeln!(out, "  rankdir=LR;").unwrap();
        writeln!(out, "  node [style=filled fontname=\"Helvetica\"];").unwrap();

        for idx in self.graph.node_indices() {
            let node = &self.graph[idx];
            if node.coord == "__ROOT__" {
                continue;
            }
            let (color, font) = match &node.risk {
                Some(Severity::Critical) => ("#ff4444", "white"),
                Some(Severity::High) => ("#ff8800", "white"),
                Some(Severity::Medium) => ("#ffcc00", "black"),
                Some(Severity::Low) => ("#88cc88", "black"),
                Some(Severity::Info) => ("#aaaaff", "black"),
                None => {
                    if node.is_direct {
                        ("#4488ff", "white")
                    } else {
                        ("#eeeeee", "black")
                    }
                }
            };
            let risk_label = node
                .risk
                .as_ref()
                .map(|r| format!("\\n[{}]", r.label()))
                .unwrap_or_default();
            writeln!(
                out,
                "  {} [label=\"{}\\n{}{}\" shape=box fillcolor=\"{}\" fontcolor=\"{}\"];",
                idx.index(),
                node.coord,
                node.version,
                risk_label,
                color,
                font
            )
            .unwrap();
        }

        for edge in self.graph.edge_indices() {
            let (from, to) = self.graph.edge_endpoints(edge).unwrap();
            if self.graph[from].coord == "__ROOT__" {
                continue;
            }
            writeln!(out, "  {} -> {};", from.index(), to.index()).unwrap();
        }

        // Root -> direct edges
        if let Some(&root_idx) = self.node_index.get("__ROOT__") {
            for child in self.graph.neighbors(root_idx) {
                let node = &self.graph[child];
                if node.coord != "__ROOT__" {
                    writeln!(out, "  ROOT [label=\"[PROJECT]\" shape=house fillcolor=\"#222222\" fontcolor=white];").unwrap();
                    writeln!(out, "  ROOT -> {};", child.index()).unwrap();
                }
            }
        }

        writeln!(out, "}}").unwrap();
        out
    }

    /// Render as JSON adjacency list
    pub fn to_json(&self) -> String {
        let mut nodes: Vec<serde_json::Value> = Vec::new();
        let mut edges: Vec<serde_json::Value> = Vec::new();

        for (idx, node) in self.graph.node_indices().map(|i| (i, &self.graph[i])) {
            if node.coord == "__ROOT__" {
                continue;
            }
            nodes.push(serde_json::json!({
                "id": idx.index(),
                "coord": node.coord,
                "version": node.version,
                "is_direct": node.is_direct,
                "risk": node.risk.as_ref().map(|r| r.label()),
            }));
        }

        for edge in self.graph.edge_indices() {
            let (from, to) = self.graph.edge_endpoints(edge).unwrap();
            let edata = &self.graph[edge];
            if self.graph[from].coord == "__ROOT__" {
                continue;
            }
            edges.push(serde_json::json!({
                "from": from.index(),
                "to": to.index(),
                "scope": edata.scope,
            }));
        }

        serde_json::to_string_pretty(&serde_json::json!({
            "nodes": nodes,
            "edges": edges,
        }))
        .unwrap_or_default()
    }

    /// Render ASCII tree starting from direct dependencies
    pub fn to_ascii_tree(&self, risk_map: &HashMap<String, Severity>, max_depth: usize) -> String {
        use colored::*;
        let mut out = String::new();

        out.push_str(&format!(
            "{}\n",
            "══ Dependency Tree ══════════════════════════════════════════"
                .cyan()
                .bold()
        ));

        let root_idx = self.node_index.get("__ROOT__");
        if root_idx.is_none() {
            out.push_str("  (no dependencies found)\n");
            return out;
        }

        let root = *root_idx.unwrap();
        let neighbors: Vec<_> = self.graph.neighbors(root).collect();

        for (i, child_idx) in neighbors.iter().enumerate() {
            let is_last = i == neighbors.len() - 1;
            let node = &self.graph[*child_idx];
            self.render_node(&mut out, node, risk_map, is_last, "", 0, max_depth);
        }

        out
    }

    fn render_node(
        &self,
        out: &mut String,
        node: &NodeData,
        risk_map: &HashMap<String, Severity>,
        is_last: bool,
        prefix: &str,
        depth: usize,
        max_depth: usize,
    ) {
        use colored::*;
        if node.coord == "__ROOT__" {
            return;
        }

        let connector = if is_last { "└── " } else { "├── " };
        let child_prefix = if is_last {
            format!("{}    ", prefix)
        } else {
            format!("{}│   ", prefix)
        };

        let severity = risk_map.get(&node.coord);
        let (icon, label) = match severity {
            Some(Severity::Critical) => (
                "💀",
                format!("{}:{}", node.coord, node.version)
                    .red()
                    .bold()
                    .to_string(),
            ),
            Some(Severity::High) => (
                "🔴",
                format!("{}:{}", node.coord, node.version).red().to_string(),
            ),
            Some(Severity::Medium) => (
                "🟡",
                format!("{}:{}", node.coord, node.version)
                    .yellow()
                    .to_string(),
            ),
            Some(Severity::Low) => (
                "🟢",
                format!("{}:{}", node.coord, node.version)
                    .green()
                    .to_string(),
            ),
            Some(Severity::Info) => (
                "ℹ️ ",
                format!("{}:{}", node.coord, node.version)
                    .blue()
                    .to_string(),
            ),
            None => {
                if node.is_direct {
                    (
                        "📦",
                        format!("{}:{}", node.coord, node.version)
                            .cyan()
                            .to_string(),
                    )
                } else {
                    (
                        "  ",
                        format!("{}:{}", node.coord, node.version)
                            .dimmed()
                            .to_string(),
                    )
                }
            }
        };

        let risk_badge = match severity {
            Some(s) => format!(" [{}]", s.label()).dimmed().to_string(),
            None => String::new(),
        };

        out.push_str(&format!(
            "{}{}{} {}{}\n",
            prefix, connector, icon, label, risk_badge
        ));

        if depth < max_depth {
            let children: Vec<_> = self
                .graph
                .neighbors(*self.node_index.get(&node.coord).unwrap())
                .collect();

            for (i, child_idx) in children.iter().enumerate() {
                let child_node = &self.graph[*child_idx];
                let child_is_last = i == children.len() - 1;
                self.render_node(
                    out,
                    child_node,
                    risk_map,
                    child_is_last,
                    &child_prefix,
                    depth + 1,
                    max_depth,
                );
            }
        }
    }
}
